export const LITEPROPS_SET_PROP = 'LITEPROPS_SET_PROP';
export const LITEPROPS_UNSET_PROP = 'LITEPROPS_UNSET_PROP';
export const LITEPROPS_HIGHLIGHT_EVENT = 'LITEPROPS_HIGHLIGHT_EVENT';
export const LITEPROPS_UNHIGHLIGHT_EVENT = 'LITEPROPS_UNHIGHLIGHT_EVENT';
